USE MASTER
GO
CREATE DATABASE SERV_TEC_DB
ALTER DATABASE SERV_TEC_DB COLLATE Latin1_General_CI_AI; 
GO
USE SERV_TEC_DB

GO

CREATE TABLE CategoriaArticulo (
IDCat BIGINT NOT NULL PRIMARY KEY IDENTITY (1000000, 1),
DescripcionCat VARCHAR (50) NOT NULL UNIQUE
);
