CREATE TRIGGER TR_AsignarEmpleadoPresupuestoAceptado
ON PRESUPUESTOS

AFTER UPDATE
AS
BEGIN
	IF(SELECT COUNT(*) FROM INSERTED) = 1 -- VERIFICAR SI SOLO SE HIZO EL CAMBIO EN UNA SOLA FILA
	BEGIN
		IF EXISTS ( --VERIFICAR SI LA REPARACION NO TIENE TECNICO, TIENE EL PRESUPUESTO ACEPTADO Y EL ESTADO ESTA EN PRESUPUESTADO
		SELECT *
		FROM REPARACIONES R
		INNER JOIN INSERTED I ON R.IDREPARACION = I.IDREPARACION
		WHERE R.IDEMPLEADO IS NULL -- LA REPARACION NO TIENE QUE TENER TECNICO
		AND R.IDESTADO = 3 -- EL ESTADO TIENE QUE SER PRESUPUESTADO
		AND I.ACEPTADO = 1 -- EL PRESUPUESTO TIENE QUE ESTAR ACEPTADO
		)
		BEGIN 
			DECLARE @AsignarEmpleadoID BIGINT;

			SELECT TOP 1 @AsignarEmpleadoID = E.IDEMPLEADO -- BUSCAR EL TECNICO CON MENOS REPARACIONES ASIGNADAS
			FROM EMPLEADOS E
			LEFT JOIN REPARACIONES R ON E.IDEMPLEADO = R.IDEMPLEADO AND R.IDESTADO != 6
		--	WHERE E.ACTIVO != 0  EMPLEADO TIENE QUE ESTAR ACTIVO
			GROUP BY E.IDEMPLEADO --SE AGRUPA POR EMPLEADO
			ORDER BY COUNT(R.IDREPARACION); --SE ORDENA DE MENOR A MAYOR

			UPDATE REPARACIONES
			SET IDEMPLEADO = @AsignarEmpleadoID --ASIGNAR TECNICO
			FROM REPARACIONES R
			INNER JOIN INSERTED I ON R.IDREPARACION = I.IDREPARACION 
			WHERE R.IDEMPLEADO IS NULL
			AND R.IDESTADO = 3
			AND I.ACEPTADO = 1;

			PRINT 'PRESUPUESTO ACEPTADO, REPARACION ASIGNADA AL TECNICO CON MENOS REPARACIONES ASIGNADAS'
		END
	END
END;